### ISSUE TITLE
Ustawienie błędu w encji to jakiś wzorzec?

### ISSUE THREAD

**Issue by EmilMassey** [stud3nt/test-empressia#1]
Skąd takie rozwiązanie?

https://github.com/stud3nt/test-empressia/blob/9fa1eeb3343f7a39f3b6b06697f9d36197f9d8c5/src/Entity/ApartmentReservation.php#L230

**Comment by stud3nt** [comment]
Skrót wynikający z ograniczeń czasowych.
Tak naprawdę to dane nt. możliwości wynajmu powinny być ładowane do
całkowicie odrębnego modelu (np. CheckReservationDataResponse);

Pozdrawiam,
Andrzej Sokolnicki


śr., 27 maj 2020 o 13:48 Emil Masiakowski <notifications@github.com>
napisał(a):

**Comment by EmilMassey** [comment]
Jasne, dzięki za odpowiedź.
