### ISSUE TITLE
Do czego służą metody AbstractEntity?

### ISSUE THREAD

**Issue by EmilMassey** [stud3nt/test-empressia#2]
Na przykład `getClass()`

**Comment by stud3nt** [comment]
AbstractEntity wziąłem z innego mojego projektu, gdzie funkcjonuje EntityConverter (konwersja encji do tablicy dla front-endu i w drugą stronę).
Metody służą do prostego i szybkiego identyfikowania danych klasy;

**Comment by EmilMassey** [comment]
Ok, dzięki. Pewnie to działało podobnie do tego? https://symfony.com/doc/current/components/serializer.html

**Comment by stud3nt** [comment]
Nie do końca. Próbowałem stworzyć własny serializer, wzorujący się na autorskim rozwiązaniu z poprzedniego miejsca pracy:
https://github.com/stud3nt/g-downloader/blob/master/src/Converter/EntityConverter.php
Muszę jednak uczcziwie stwierdzić, że eksperyment udał mi się, cytując klasyka "tak średnio, bym powiedział. Tak średnio".
