### ISSUE TITLE
Dlaczego argument jest przekazywany przez referencję?

### ISSUE THREAD

**Issue by EmilMassey** [stud3nt/test-empressia#3]
https://github.com/stud3nt/test-empressia/blob/9fa1eeb3343f7a39f3b6b06697f9d36197f9d8c5/src/Manager/ApartmentReservationManager.php#L47

**Comment by stud3nt** [comment]
Funkcja do poprawki - nie powinna niczego zwracać, referencja zostaje. W obecnej postaci wprowadza w błąd.

Dlaczego referencja? - bo zadaniem tej funkcji jest zmodyfikowanie (ustawienie wartości) określonej instancji obiektu. 
Gdyby funkcja miała za zadanie zwrócić inną odpowiedź/obiekt, a tego przekazywanego do niej nie  ruszać, to wtedy - rzecz jasna - referencji nie powinno być.

**Comment by EmilMassey** [comment]
```
class A {
    private $foo;
    
    public function setFoo(string $foo) { $this->foo = $foo; }
    
    public function __toString() { return $this->foo; }
}

function bar(A $a) {           // bez referencji
    $a->setFoo('bar');
}

$a = new A();
$a->setFoo('foo');

echo $a;

bar($a);

echo $a;
```

**Comment by stud3nt** [comment]
Rzeczywiście.

_objects are passed by references by default_
https://www.php.net/manual/en/language.oop5.references.php

Czyli referencję stosuje się do zwykłych zmiennych.
Do klas - nie trzeba. I nie ma tu znaczenia, czy utworzymy więcej instancji klasy A, a potem przekażemy do foo() losową z nich.

Tyle lat w błędzie, wstyd :(
